
version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_lojaManoel
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: MinhaSenh@123
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - loja_network

  api:
    build: .
    container_name: api_loja_manoel
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=LojaManoel;User Id=sa;Password=MinhaSenh@123;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    networks:
      - loja_network

volumes:
  sqlserver_data:

networks:
  loja_network:
    driver: bridge